global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "mongo_loader"
    static_configs:
      - targets: ["mongo_loader_replica_1:2112, mongo_loader_replica_2:2112, mongo_loader_replica_3:2112"]
